Update Sponsors and Sponsorhip information
ThePHPF/thephp.foundation pull request #156
Opened 2024-07-15 15:17 UTC by pronskiy

2024-07-15 18:34 UTC, saundefined approved these changes
This looks great, thank you!

Maybe add a check for sponsors in the level?
Otherwise, silver sponsors have a heading but no companies (I guess temporarily, but still) 😀

2024-07-15 18:34 UTC, saundefined commented on source/_layouts/sponsors.html
> +</div>
```suggestion
{% if sponsors['Platinum']|length > 0 %}
<h2 id="sponsors_platinum">Platinum Sponsors</h2>
<div class="grid grid-cols-4 gap-4 mb-8">
    {% for sponsor in sponsors['Platinum'] %}
    <div>
        <a href="{{ sponsor.website }}"
           class="block no-underline" target="_blank" rel="noopener noreferrer">
            <div class="mb-2 p-2">
                <img class="h-32 rounded w-full object-contain object-center"
                     src="{{ sponsor.image }}" alt="sponsor.name"/>
            </div>
            <div class="overflow-hidden overflow-ellipsis whitespace-nowrap text-gray-900 font-medium mb-4 text-center">
                <a class="no-underline text-inherit" href="{{ sponsor.website }}">{{ sponsor.name }}</a>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endif %}
```

2024-07-15 18:34 UTC, saundefined commented on source/_layouts/sponsors.html
> +</div>
```suggestion
{% if sponsors['Gold']|length > 0 %}
<h2 id="sponsors_gold">Gold Sponsors</h2>
<div class="grid grid-cols-6 gap-4 text-base mb-8">
    {% for sponsor in sponsors['Gold'] %}
    <div>
        <a href="{{ sponsor.website }}"
           class="block no-underline" target="_blank" rel="noopener noreferrer">
            <div class="mb-2 p-2">
                <img class="h-24 rounded w-full object-contain object-center"
                     src="{{ sponsor.image }}" alt="sponsor.name"/>
            </div>
            <div class="overflow-hidden overflow-ellipsis whitespace-nowrap text-gray-900 font-medium mb-4 text-center">
                <a class="no-underline text-inherit" href="{{ sponsor.website }}">{{ sponsor.name }}</a>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endif %}
```

2024-07-15 18:34 UTC, saundefined commented on source/_layouts/sponsors.html
> +</div>
```suggestion
{% if sponsors['Silver']|length > 0 %}
<h2 id="sponsors_silver">Silver Sponsors</h2>
<div class="grid grid-cols-6 gap-4 text-sm  mb-8">
    {% for sponsor in sponsors['Silver'] %}
    <div>
        <a href="{{ sponsor.website }}"
           class="block no-underline" target="_blank" rel="noopener noreferrer">
            <div class="mb-2 p-2">
                <img class="h-24 rounded w-full object-contain object-center"
                     src="{{ sponsor.image }}" alt="sponsor.name"/>
            </div>
            <div class="overflow-hidden overflow-ellipsis whitespace-nowrap text-gray-900 font-medium mb-4 text-center">
                <a class="no-underline text-inherit" href="{{ sponsor.website }}">{{ sponsor.name }}</a>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endif %}
```

2024-07-18 09:46 UTC, saundefined reviewed
Nits for mobile

2024-07-18 09:46 UTC, saundefined commented on source/_layouts/sponsors.html
> +<div class="grid grid-cols-6 gap-4 text-base  mb-8">
```suggestion
<div class="grid grid-cols-2 lg:grid-cols-6 gap-4 text-base mb-8">
```

2024-07-18 09:46 UTC, saundefined commented on source/_layouts/sponsors.html
> +<div class="grid grid-cols-5 gap-4 text-base mb-8">
```suggestion
<div class="grid grid-cols-2 lg:grid-cols-5 gap-4 text-base mb-8">
```

2024-07-18 09:46 UTC, saundefined commented on source/_layouts/sponsors.html
> +<div class="grid grid-cols-4 gap-4 mb-8">
```suggestion
<div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
```

2024-07-18 09:46 UTC, saundefined commented on source/_layouts/sponsors.html
> +<div class="grid grid-cols-8 gap-4 text-base mb-8">
```suggestion
<div class="grid grid-cols-2 lg:grid-cols-6 gap-4 text-base mb-8">
```

2024-07-19 07:58 UTC, lwlwilliam requested changes
Some sponsors may have names that are too long to fully display.

2024-07-19 07:58 UTC, lwlwilliam commented on source/_layouts/sponsors.html
> +    <div>
```suggestion
    <div title="{{ sponsor.name }}">
```

2024-07-19 07:58 UTC, lwlwilliam commented on source/_layouts/sponsors.html
> +    <div>
```suggestion
    <div title="{{ sponsor.name }}">
```

2024-07-19 07:58 UTC, lwlwilliam commented on source/_layouts/sponsors.html
> +    <div>
```suggestion
    <div title="{{ sponsor.name }}">
```

2024-07-19 10:13 UTC, lwlwilliam requested changes

2024-07-19 10:13 UTC, lwlwilliam commented on source/_layouts/sponsors.html
> +                     src="{{ sponsor.image }}" alt="sponsor.name"/>
```suggestion
                     src="{{ sponsor.image }}" alt="{{ sponsor.name }}"/>
```

2024-07-19 10:13 UTC, lwlwilliam commented on source/_layouts/sponsors.html
> +                     src="{{ sponsor.image }}" alt="sponsor.name"/>
```suggestion
                     src="{{ sponsor.image }}" alt="{{ sponsor.name }}"/>
```

2024-07-19 10:13 UTC, lwlwilliam commented on source/_layouts/sponsors.html
> +                     src="{{ sponsor.image }}" alt="sponsor.name"/>
```suggestion
                     src="{{ sponsor.image }}" alt="{{ sponsor.name }}"/>
```

2024-07-22 09:37 UTC, merged