Add PHP Core Roundup 20
ThePHPF/thephp.foundation pull request #188
Opened 2024-11-19 16:20 UTC by Ayesh

2024-11-20 09:52 UTC, pronskiy commented
@Ayesh, great post! 
Since this one is devoted to the PHP 8.4 release, how about copying/including short paragraphs about Hooks, aviz, HTML%, and BCMath? I know you've already covered them previously, but it's be unfortunate to miss them in this post. What do you think?

2024-11-20 10:01 UTC, pronskiy requested changes

2024-11-20 10:01 UTC, pronskiy commented on source/_posts/2024-11-21-php-core-roundup-20-php84.md
> +Follow us on Twitter/X [@ThePHPF](https://twitter.com/thephpf) or  [Mastodon](https://phpc.social/@thephpf) to get the latest updates from the Foundation.
```suggestion
Follow us on Twitter/X [@ThePHPF](https://twitter.com/thephpf),  [Mastodon](https://phpc.social/@thephpf), [LinkedIn](https://www.linkedin.com/company/phpfoundation/), and [Bluesky](https://bsky.app/profile/thephpf.bsky.social) to get the latest updates from the Foundation.
```

2024-11-21 06:56 UTC, Ayesh commented
I added a somewhat minimal copy-pasta from the previous post about aviz and hooks, bcmath, and dom.

2024-11-21 06:57 UTC, Ayesh commented
I'll also add Lazy objects, please do not merge yet :)

2024-11-21 13:22 UTC, Ayesh commented
Ready for review :)

I tried to keep the post minimal to avoid duplication, and linked to all available doc pages on php.net now.

I will keep an eye and update links. php/doc-en#3872) tracks them.

2024-11-21 13:23 UTC, pronskiy commented on source/_posts/2024-11-21-php-core-roundup-20-php84.md
> +We are thrilled to announce that after a year of hard work, dedication, and collaboration, **PHP 8.4** is officially here!
```suggestion
We are thrilled to announce that after a year of hard work, dedication, and collaboration, [**PHP 8.4**](https://www.php.net/releases/8.4/) is officially here!
```

2024-11-21 13:29 UTC, merged